trigger:
  - main

resources:
  repositories:
    - repository: templates
      type: github
      name: actions/checkout
      ref: refs/tags/v4

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
  - checkout: templates
  - template: steps/build.yml@templates
